repos:
  - repo: local
    hooks:
      - id: ruff
        language: unsupported
        name: Ruff
        files: '.+\.py$'
        entry: ruff check
        verbose: true

      - id: mypy
        language: unsupported
        name: Mypy
        files: '.+\.py$'
        entry: mypy
        verbose: true
